/**
 * EMOJI DATA
 *
 * Non exhaustive list of emojis and aproximate physical properties.
 *
 * The main goal of this is to serve as source of data for interesting visualizations, that's why most emojis related to faces are skipped as we only need one for visualizations.
 */

import data from './data.json';

export type DataSource = {
  values: {
    height?: { value: number }; // centimeters
    speed?: { value: number }; // km/h
  };
  url?: string;
  description?: string;
};

/**
 * Empty space on each side of the emoji's artwork, as percentages of the 1em
 * artwork square, in CSS inset order: `[top, right, bottom, left]`.
 *
 * `[0, 0, 0, 0]` means the artwork fills the square edge to edge. Measured by
 * `reference/measure-bounding-boxes.mjs`, which documents the square itself —
 * `measureText` cannot produce these, because Apple Color Emoji reports one
 * identical ink box for every glyph.
 */
export type BoundingBox = [
  top: number,
  right: number,
  bottom: number,
  left: number,
];

export type EmojiEntry = {
  tags?: string[];
  name: string;
  sources: DataSource[];
  /** Keyed by emoji vendor. Only Apple is measured; it is used everywhere. */
  boundingBox?: { apple: BoundingBox };
};

export type EmojiDatabase = Record<string, EmojiEntry>;

export const CATEGORIES = [
  'animals',
  'nature',
  'objects',
  'landmarks',
] as const;

/* `as unknown as` rather than a direct cast: TypeScript infers `number[]` for
   the boundingBox arrays in the imported JSON, which is not assignable to the
   4-tuple `BoundingBox`. The tuple is the shape the file actually holds — it is
   generated by `reference/measure-bounding-boxes.mjs`, which always writes four
   numbers — so asserting it here is sound. */
export const emojiDatabase: EmojiDatabase = data as unknown as EmojiDatabase;

/** Every emoji in data.json is measured; this covers a hand-added entry. */
const UNMEASURED: BoundingBox = [0, 0, 0, 0];

function boxOf(entry: EmojiEntry): BoundingBox {
  return entry.boundingBox?.apple ?? UNMEASURED;
}

export type EmojiData = {
  emoji: string;
  height: number; // centimeters
  label: string;
  tags: string[];
  boundingBox: BoundingBox;
};

export function getEmojiData(): EmojiData[] {
  return Object.entries(emojiDatabase)
    .map(([emoji, entry]) => {
      const heightSource = entry.sources.find((s) => s.values.height);
      const height = heightSource?.values.height?.value ?? 0;
      return {
        emoji,
        height,
        label: entry.name,
        tags: entry.tags || [],
        boundingBox: boxOf(entry),
      };
    })
    .filter((item) => item.height > 0.01)
    .sort((a, b) => a.height - b.height);
}

export type EmojiSpeedData = {
  emoji: string;
  speed: number; // km/h
  label: string;
  tags: string[];
  boundingBox: BoundingBox;
  source?: { description?: string; url?: string };
};

export function getEmojiSpeedData(): EmojiSpeedData[] {
  return Object.entries(emojiDatabase)
    .map(([emoji, entry]) => {
      const speedSource = entry.sources.find((s) => s.values.speed);
      const speed = speedSource?.values.speed?.value ?? 0;
      return {
        emoji,
        speed,
        label: entry.name,
        tags: entry.tags || [],
        boundingBox: boxOf(entry),
        source:
          speedSource && (speedSource.description || speedSource.url)
            ? { description: speedSource.description, url: speedSource.url }
            : undefined,
      };
    })
    .filter((item) => item.speed > 0)
    .sort((a, b) => a.speed - b.speed);
}

export type EmojiGlyph = {
  emoji: string;
  label: string;
  tags: string[];
  boundingBox: BoundingBox;
};

/**
 * Every entry, unfiltered and in database order — unlike the two functions
 * above, which drop entries lacking the value they visualize. Used by the
 * localhost-only /debug-size page, which inspects the glyphs themselves and so
 * must not hide the ones whose physical data is still missing.
 */
export function getAllEmojis(): EmojiGlyph[] {
  return Object.entries(emojiDatabase).map(([emoji, entry]) => ({
    emoji,
    label: entry.name,
    tags: entry.tags || [],
    boundingBox: boxOf(entry),
  }));
}
